theme: jekyll-theme-cayman
layout: page
title: "La veille technologique"
description: Second GRC article
permalink: /cyber-links/2nd_article
theme: jekyll-theme-cayman
title: [Présentation de certains APT](https://www.mandiant.com/resources/insights/apt-groups) 

description: "Que la sécurité informatique et rien que la cybersécurité"
picture:
  path: CyberlinkS7.png

