theme: jekyll-theme-hacker
title: Cyber-links's first article
description: First GRC article
layout: page
title: La veille technologique
description: Second GRC article
permalink: /cyber-links/2nd_article.md
